name: e_commerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  animated_snack_bar: ^0.4.0
  animations: ^2.0.8
  bloc: ^8.1.2
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dots_indicator: ^3.0.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_image: ^0.0.6+1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  getwidget: ^4.0.0
  go_router: ^10.1.2
  image_picker: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/CategoryIcons/
    - assets/images/appliances_logo/
    - assets/icons/svg/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts\static\PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/static/PlusJakartaSans-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/static/PlusJakartaSans-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/static/PlusJakartaSans-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/static/PlusJakartaSans-LightItalic.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/static/PlusJakartaSans-Regular.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/static/PlusJakartaSans-SemiBoldItalic.ttf
          style: italic
