// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-KmKkm_O991D-sgR_MsKWpqDcLPzQPlg',
    appId: '1:148823000814:web:7a64bf2ba778268f1395ff',
    messagingSenderId: '148823000814',
    projectId: 'alesraa-4e1ae',
    authDomain: 'alesraa-4e1ae.firebaseapp.com',
    storageBucket: 'alesraa-4e1ae.appspot.com',
    measurementId: 'G-HHRR0889Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjLbj3tgWDvasZYmK8oJnyHSf_5zEYNzo',
    appId: '1:148823000814:android:4a1b2da240a4feb31395ff',
    messagingSenderId: '148823000814',
    projectId: 'alesraa-4e1ae',
    storageBucket: 'alesraa-4e1ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6bptDxA3H3oU0E1ARgEdaF_oEcQZHqI',
    appId: '1:148823000814:ios:df69acfda84f11621395ff',
    messagingSenderId: '148823000814',
    projectId: 'alesraa-4e1ae',
    storageBucket: 'alesraa-4e1ae.appspot.com',
    iosBundleId: 'com.abdelmoneam.alesraa.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6bptDxA3H3oU0E1ARgEdaF_oEcQZHqI',
    appId: '1:148823000814:ios:df69acfda84f11621395ff',
    messagingSenderId: '148823000814',
    projectId: 'alesraa-4e1ae',
    storageBucket: 'alesraa-4e1ae.appspot.com',
    iosBundleId: 'com.abdelmoneam.alesraa.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-KmKkm_O991D-sgR_MsKWpqDcLPzQPlg',
    appId: '1:148823000814:web:e78757edc7a3316e1395ff',
    messagingSenderId: '148823000814',
    projectId: 'alesraa-4e1ae',
    authDomain: 'alesraa-4e1ae.firebaseapp.com',
    storageBucket: 'alesraa-4e1ae.appspot.com',
    measurementId: 'G-M3SY9K219B',
  );
}
